
from concurrent.futures import thread
from importlib import metadata
from json import load
from pyexpat.errors import messages

from langgraph_tool_backend import chatbot, retrieve_all_threads # we have made our chatbot object in the backend so we can used use that object from there or any other func , u can invoke the chatbot directly retrive_all_threads is our sqlite db for short term memory
from langchain_core.messages import HumanMessage

from langchain_groq import ChatGroq
from dotenv import load_dotenv
import uuid
import streamlit as st

# in this database backend only change u have to do is in the session setup( in the chat_threads to see the diff see the previous front streaming code and this one)
# why changes in this = see in previous code as soon the we start out chatbot the chat_threads is null means there is no pevious thread_id this was because we were using imemorysaver because of this if we refresh the page or restart our bot after 2-3 days there will be no history because it is stored in ram but now we are using sql lite database we have the previous chat and history stored because of this we can show the previous history, we were not having permanent storage(because we have past threads) but now we have it 
# in the chat threads we will ask backend that how many threds we have total no of threads, for this we will make a funct that tell us the total no of threads present and take that threads and fill in the  chatthreads  
def generate_thread_id():#-> resume chatbot feature 
     thread_id=uuid.uuid4()
     return thread_id # it will generate random new thread id  

# to make the new pageload 1st we need to clear the chat means the chat we we stored in the message_history in the session_setup
# as soon as the user clicked the new chat the ui of the old chat should be cleaned there should be empty chat and u should watched plain empty chat  where user can talk about neww 
# so what we gonna do we will clear/empty the ongoing conversation doin this our ui will be cleaned and we can load new conversations 
#2nd task
#-> on Click if new chat open a new chat window 

#   - generate a new thread_id

#   - save it in session means the thread_id generated by the uuid

#@   - reset message history (in out code in sessionstate we created a variable called messageshistory that stores all the history bw user and ai and we loop in this and print all the messages[in load conversation history] )


def  reset_chat(): # resume chatbot feature, a utility funct
     thread_id= generate_thread_id() #generates new thread_id
     st.session_state['thread_id']=thread_id
     add_thread(st.session_state['thread_id']) # when the button is clicked 
     st.session_state['message_history']=[] #emptys the message 

# so we have done it now can can chat bew conversations but there is a prob we soon as we clicked new chat old threadid id gone we cannot some how we need to retain it 
# here comes task 3 of the resume chat feature 
#3rd this will be the part of the session means will be be not wiped of 
#-> create a list to store all thread_ids[ create a list inside a session [session_setup]which will store the thread id ]

#-> load all the thread ids in the sidebar

#-> convert the sidebar text to clickable buttons :
   
# for this u simple chat the st.text to st.button in the side bar ui in the chat_threads 3d one in that  and make the thread ID a str  ->



#1st so how many times we gonna ad tread id to this list 2 times 1st when the page reloads and 2nd when the new chat button is clicked for this we gonna make a utility(means the extra functions) funct 

def add_thread(thread_id):  #  to add thread id in list (chat_threads), resume chat feature
     if thread_id not in st.session_state['chat_threads']: # if the thread id is not in the list{chat threads} we gonna append in then
          st.session_state['chat_threads'].append(thread_id)






#-> on click of a particular thread id load the particlular conversations, make thread_id to button so that when we click it it will show the conversations 


#4th

#-> on click of a particular thread id load the particlular conversations 
#- exttract the thread id and fetch all the messages from the thread
# fill the messages in message history
#-> for this also we make a utility fuc in that we will give it a particular thread id and it will return the list of messages in that 
#In LangGraph, the difference between get_state (assumed from the typo "getdate") and get_state_history is the scope of checkpoints they retrieve for a given thread. get_state retrieves only the single, most recent snapshot of the graph's state, whereas get_state_history returns a chronological list of all state checkpoints generated during the execution histor

def  load_conversations(thread_id): #-> gives the list of messages in that particular  thread_i
     return chatbot.get_state(config={'configurable': {'thread_id':thread_id}}).values['messages'] # we full the full state info means messages in the current node in our case theres only node , in get_state u pass config(thread_id)

# this load conversation is for the the partucular thread_id to load 
# the last task is as soon as we click the button means the thread id that conversation should load
# now we will do changes in the ui part means sidebar ui




#session setup we are setuping three things here messagehistroy,thread_id and chatthreads

if "message_history" not in st.session_state: #checking if mess history is there in session if not we will add it 
     st.session_state['message_history'] =[]  # we added it and it will be a list, session state is a dictionary and we aaded message-history  this is a key  and value is list , adding messages from the particular thread to list and storing in the session means message history in sessions

if 'thread_id' not in st.session_state: # if we have not defined thread_id manually  ofc we are not generating thats why we are using the uuid library
     st.session_state['thread_id']= generate_thread_id() # iska jo bhi output rehega means thread id wo session ke thread id ho jaiga  , currently jo bhi chat chal rahi hai ham uss thread id ko store kr rahe hai session me ye work ye code kr rah hai 
     # st sessions thread id == thred id produced by uuid 
#chatthreads is name of the list , so how many times we gonna ad tread id to this list 2 times 1st when the page reloads and 2nd when the new chat button is clicked
if 'chat_threads' not in st.session_state: # how many total thread ids we have we are storing that in the session
     st.session_state['chat_threads']=retrieve_all_threads() # here initiallizing empty list we will just call the retrieve_all_threads 
# as soon ass this retrive funct gets called it will return the total number of thread id and it will get added in the chatthreads 
# after all this when the page loads u will add  the current thread id in the session state and store it  in the chat threads  call the add_threads 
add_thread(st.session_state['thread_id'])
# so u can see se can see multiple thread_ids in the left 


#CONFIG= {'configurable' : {'thread_id': st.session_state['thread_id']}}
# this uper config is correct but for the langsmith we are writing in this way if u wanna know the problem go to the genxagentic and in that observability in langgraph u can see the problem
#langsmith config problem fix
CONFIG= {
    'configurable': {"thread_id": st.session_state['thread_id']},
    'metadata': {
        'thread_id': st.session_state['thread_id']
    },
    'run_name': 'chat_turn'                             #all the traces are stored in there respective thread 
    }
#this is for that we wwant out thread ad in thread that particualer traces means the convo in that thread  so it will show thread_ids and each convo means each traces 

# side bar Ui

st.sidebar.title("langgraph_chatbot")

if st.sidebar.button("New chat"): # if the new chat button is clicked simple return reset chat it will do the things 
     reset_chat()

st.sidebar.header("Your conversations ")
# now we wanna load  all the thread_ ids for that we make a loop in sidebar.text to see in the left side 

for thread_id in st.session_state['chat_threads'][::-1]: # to diaplay chat threads  , [::-1] this measn we are reversing the list why se whem u click new chat your new chart come below the old send but we what when we click it ourr new chat comes above the old chat like the so we did this 
     if st.sidebar.button(str(thread_id)):  # to display the session thread id  below the conversations  sessions thread_id == thread_id generated by the uuid
          st.session_state['thread_id']= thread_id  # we will store this particular thread id in the session_state for future 
          messages=load_conversations(thread_id)                               # if this particular button is click than we will

          # compatibility break na ho uske lia coode 
          temp_messages=[]
          for message in messages:
               if isinstance(message,HumanMessage):   # if current message instance is human message  if we will store in the role variable "user"
                    role='user'
               else:
                    role="ai" 

               temp_messages.append({"role":role, "content":message.content})

               # in the above the the previous messages we get the messages in the format ["role":"user","content": hi]-> user , {'role':'assiatant', 'content':"hello"} this swas th format, the probelm we were getting all the unusefull message like metadata for that we are converting this message format to this once which we have defined in this line so that messages history loads properly
               # we will come out of the loop and equal this temp message to session states message history

          st.session_state['message_history']=temp_messages # so this gives in specific format


          
#loading the conversation history  -> how to print message_history 
for message in st.session_state['message_history']:
     with st.chat_message(message['role']): #message becuase it is dict and all things ars stored in it
          st.text(message['content'])     
    


user_input=st.chat_input("Type here!")
 

if user_input: #if user gives input 

    # add the messages to the message_history
    st.session_state['message_history'].append({'role':'user', 'content':user_input}) #dict to store the message as per role 

    with st.chat_message('user'):
        st.text(user_input)

    # u can invoke ur chatbot and while invoking u have 2 send 2 things here the thread id  and the initial state, while invoking u have to give this 2 things c
    #response=chatbot.invoke({'messages':[HumanMessage(content=user_input)]},config=CONFIG)

    #ai_message= response['messages'][-1].content

    #  add message to message_history  below code is od adding streaming feature 
    #st.session_state['message_history'].append({'role':'ai', 'content': ai_message })
    with st.chat_message('ai'): # so we need generator how we will get it by doin langgrah.stream means chatbot.stream
            ai_message=st.write_stream(# we are just sending messagechunk content to stream and it will 
                 message_chunk.content for message_chunk, metadata in chatbot.stream(
                      {'messages': [HumanMessage(content=user_input)]},
                    config=CONFIG,
                    stream_mode='messages' #it will give as message chunk and metadata we goona loop in it 
                      
                      
                 )
                 
            )

    st.session_state['message_history'].append({'role':'ai', 'content': ai_message})