
from concurrent.futures import thread
from importlib import metadata
from json import load
from pyexpat.errors import messages

from langgraph_backend import chatbot # we have made our chatbot object in the backend so we can used use that object from there  , u can invoke the chatbot directly
from langchain_core.messages import HumanMessage

from langchain_groq import ChatGroq
from dotenv import load_dotenv
import uuid
import streamlit as st

#we will implement streaming here , to so streaming we needa UI element called chat elements we have used chat_message and chat_input
# we have status container  # u can gives updates uwhen using agents means agent is searching now booking like this what agent is doing 
# for this we gonna use write_stream st.writte_stream(pass your generator geberated by the langgraph.stream)
# so we will do changes in the  session part that we append 


# below is the resume chatbot feature 
# and a sidebar with title + a start button + a  title name "my conversations" -> in the ui setup

# generate dynamic thread id and add it to the session = see for this task in the config part u have given only 1 thread id but can clicl multiple timee (new chat) and can create new chat we dont know we cannot manually give new thread id so for this we need to make it duynamic means it will automatically generate new thread id as we click new chat for this we will use uuid task2 done see in the resume chat cell  
# after this we wanna display the thread id below the conversation




#utility functions  to gen random thread _id


def generate_thread_id():#-> resume chatbot dfeature 
     thread_id=uuid.uuid4()
     return thread_id # it will generate random new thread id  

# to make the new pageload 1st we need to clear the chat means the chat we we stored in the message_history in the session_setup
# as soon as the user clicked the new chat the ui of the old chat should be cleaned there should be empty chat and u should watched plain empty chat  where user can talk about neww 
# so what we gonna do we will clear/empty the ongoing conversation doin this our ui will be cleaned and we can load new conversations 
#2nd task
#-> on Click if new chat open a new chat window  , this task is of resume ask feature 

#   - generate a new thread_id

#   - save it in session means the thread_id generated by the uuid

#@   - reset message history (in out code in sessionstate we created a variable called messageshistory that stores all the history bw user and ai and we loop in this and print all the messages[in load conversation history] )


def  reset_chat(): # resume chatboit feature, a utility funct
     thread_id= generate_thread_id() #generates new thread_id
     st.session_state['thread_id']=thread_id
     add_thread(st.session_state['thread_id']) # when the button is clicked 
     st.session_state['message_history']=[] #emptys the message 

# so we have done it now can can chat bew conversations but there is a prob we soon as we clicked new chat old threadid id gone we cannot some how we need to retain it 
# here comes task 3 of the resume chat feature 
#3rd this will be the part of the session means will be be not wiped of 
#-> create a list to store all thread_ids[ create a list inside a session [session_setup]which will store the thread id ] -> RESUME CCHAR FEATURE TASK

#-> load all the thread ids in the sidebar

#-> convert the sidebar text to clickable buttons :
   
# for this u simple chat the st.text to st.button in the side bar ui in the chat_threads 3d one in that  and make the thread ID a str  ->



#1st so how many times we gonna ad tread id to this list 2 times 1st when the page reloads and 2nd when the new chat button is clicked for this we gonna make a utility(means the extra functions) funct 

def add_thread(thread_id):  #  to add thread id in list (chat_threads)
     if thread_id not in st.session_state['chat_threads']: # if the thread id is not in the list{chat threads} we gonna append in then
          st.session_state['chat_threads'].append(thread_id)






#-> on click of a particular thread id load the particlular conversations, make thread_id to button so that when we click it it will show the conversations 


#4th

#-> on click of a particular thread id load the particlular conversations -> RESUME CHAT FEATURE TASK 
#- exttract the thread id and fetch all the messages from the thread
# fill the messages in message history
#-> for this also we make a utility fuc in that we will give it a particular thread id and it will return the list of messages in that 
#In LangGraph, the difference between get_state (assumed from the typo "getdate") and get_state_history is the scope of checkpoints they retrieve for a given thread. get_state retrieves only the single, most recent snapshot of the graph's state, whereas get_state_history returns a chronological list of all state checkpoints generated during the execution histor

def  load_conversations(thread_id): #-> gives the list of messages in that particular  thread_i
     return chatbot.get_state(config={'configurable': {'thread_id':thread_id}}).values['messages'] # we full the full state info means messages in the current node in our case theres only node , in get_state u pass config(thread_id)

# this load conversation is for the the partucular thread_id to load 
# the last task is as soon as we click the button means the thread id that conversation should load
# now we will do changes in the ui part means sidebar ui




#session setup

if "message_history" not in st.session_state: #checking if mess history is there in session if not we will add it 
     st.session_state['message_history'] =[]  # we added it and it will be a list, session state is a dictionary and we aaded message-history  this is a key  and value is list 

if 'thread_id' not in st.session_state: # if we have not defined thread_id manually  ofc we are not generating thats why we are using the uuid library
     st.session_state['thread_id']= generate_thread_id() # iska jo bhi output rehega means thread id wo session ke thread id ho jaiga  
     # st sessions thread id == thred id produced by uuid 
#chatthreads is name of the list , so how many times we gonna ad tread id to this list 2 times 1st when the page reloads and 2nd when the new chat button is clicked
if 'chat_threads' not in st.session_state:
     st.session_state['chat_threads']=[]
# after all this when the page loads u will add  the current thread id in the session state and store it  in the chat threads  call the add_threads 
add_thread(st.session_state['thread_id'])
# so u can see se can see multiple thread_ids in the left 


CONFIG= {'configurable' : {'thread_id': st.session_state['thread_id']}}


# side bar Ui

st.sidebar.title("langgraph_chatbot")

if st.sidebar.button("New chat"): # if the new chat button is clicked simple return reset chat it will do the things 
     reset_chat()

st.sidebar.header("Your conversations ")
# now we wanna load  all the thread_ ids for that we make a loop in sidebar.text to see in the left side 

for thread_id in st.session_state['chat_threads'][::-1]: # to diaplay chat threads  , [::-1] this measn we are reversing the list why se whem u click new chat your new chart come below the old send but we what when we click it ourr new chat comes above the old chat like the so we did this 
     if st.sidebar.button(str(thread_id)):  # to display the session thread id  below the conversations  sessions thread_id == thread_id generated by the uuid
          st.session_state['thread_id']= thread_id  # we will store this particular thread id in the session_state for future 
          messages=load_conversations(thread_id)                               # if this particular button is click than we will

          # compatibility break na ho uske lia coode 
          temp_messages=[]
          for message in messages:
               if isinstance(message,HumanMessage):   # if current message instance is human message  if we will store in the role variable "user"
                    role='user'
               else:
                    role="ai" 

               temp_messages.append({"role":role, "content":message.content})

               # in the above the the previous messages we get the messages in the format ["role":"user","content": hi]-> user , {'role':'assiatant', 'content':"hello"} this swas th format, the probelm we were getting all the unusefull message like metadata for that we are converting this message format to this once which we have defined in this line so that messages history loads properly
               # we will come out of the loop and equal this temp message to session states message history

          st.session_state['message_history']=temp_messages # so this gives in specific format


          
#loading the conversation history  -> how to print message_history 
for message in st.session_state['message_history']:
     with st.chat_message(message['role']): #message becuase it is dict and all things ars stored in it
          st.text(message['content'])     
    


user_input=st.chat_input("Type here!")


if user_input: #if user gives input 

    # add the messages to the message_history
    st.session_state['message_history'].append({'role':'user', 'content':user_input}) #dict to store the message as per role 

    with st.chat_message('user'):
        st.text(user_input)

    # u can invoke ur chatbot and while invoking u have 2 send 2 things here the thread id  and the initial state, while invoking u have to give this 2 things c
    #response=chatbot.invoke({'messages':[HumanMessage(content=user_input)]},config=CONFIG)

    #ai_message= response['messages'][-1].content

    #  add message to message_history  below code is od adding streaming feature 
    #st.session_state['message_history'].append({'role':'ai', 'content': ai_message })
    with st.chat_message('ai'): # so we need generator how we will get it by doin langgrah.stream means chatbot.stream
            ai_message=st.write_stream(# we are just sending messagechunk content to stream and it will 
                 message_chunk.content for message_chunk, metadata in chatbot.stream(
                      {'messages': [HumanMessage(content=user_input)]},
                    config=CONFIG,
                    stream_mode='messages' #it will give as message chunk and metadata we goona loop in it 
                      
                      
                 )
                 
            )

    st.session_state['message_history'].append({'role':'ai', 'content': ai_message})
#'''below the st write stream message_chunk.content for message_chunk, metadata in chatbot.stream
#this means we want messagechunk.content for every message chunk and metadata  in this stream and this stream object means chatbot.stream
#gives as message chunk and its metadata and after that it will print as soon as it loads
#in simple   st.write stream ke andar chatbot.stream ko call kar rahe hai usse hame 2 chiz mil rahi hai message chunk and metadata usme se 
#ham message_chunk ka content de rahe hai st.write stream ko or wo type writter effect me print kar rah hai

#and when the response is printed  using st.wrire stream we will store it in ai _messagage and store it in a session

# '''

# Till now we have implemented streming resume chat feature in this feature we have build a button called new chat from where u can start new chat for this we have to generate new thread ids for each chat for this we ave used uuid librrby that generate new random thread id and we have to first clean the old text ui and than show the new chat ui this also we have done it and load the conversations of the new chat and store that new chat in the session state , we we have also implemented that if we click the new thread id iw ill show us the messages of that id we have used fuct like gen thread reset chat load conversations 
# sincw we are using Inmemorysaver to store the conversations means short term memory means we are storing it in ram  but there is a prob onde u reload ur page or restart your bot all the coversations which u did is deleted or it is empty there is no permanent storage so  have we will replace the memorysaver  woth another checkpointer in this we will integrate out chatbot with batabases we will store the conversations bw user and ai in this database so if u refresh or come after 2-3 days u can resume the chat 